export enum JOB_APPLIED_STATUS_ENUM {
  YET_TO_SCREEN = 'YET_TO_SCREEN',
  UNDER_SCREENING = 'UNDER_SCREENING',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  WAITING_FOR_INTERVIEW_FEEDBACK = 'WAITING_FOR_INTERVIEW_FEEDBACK',
  WATING_FOR_HR_DISCUSSION = 'WATING_FOR_HR_DISCUSSION',
  YET_TO_RELEASE_OFFER = 'YET_TO_RELEASE_OFFER',
  OFFER_RELEASE = 'OFFER_RELEASE',
  OFFER_ACCEPTED_BY_CANDIDATE = 'OFFER_ACCEPTED_BY_CANDIDATE',
  REJECTED = 'REJECTED',
  ON_HOLD = 'ON_HOLD',
  ON_BOARDED = 'ON_BOARDED',
}
